# Site
name: "Ellas blog"
title: "Ellas blog"
description: "Blog om bøger, krea, mad, og andre sjove ting."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ella:
    name: Ella
    display_name: Ella
    avatar: 'assets/images/ella-dahl.jpg'
    email: ella.marie.bjorholm.dahl@gmail.com
    description: "Ella er vild med at skrive. Hun elsker bøger, krea, mad, og andre sjove ting. Så det skriver hun i sin blog, som du er ved at læse."
  vedrana:
    name: Vedrana
    display_name: Vedrana
    description: "Vedrana kan godt lide github, jekyll, html. Hun er vild med at kode og lave hjemmesider. Hun har lavet denne blog til Ella."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
permalinks:
  category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: 
adsense-data-ad-slot: 

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
