# Site
name: "Ellas blog"
title: "Ellas blog"
description: "Blog om bøger, krea, mad og andre ting man laver i fritiden."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "https://ella-dahl.github.io/blog/"
include: ["_pages"]

# Authors
authors:
  ella:
    name: Ella
    display_name: Ella
    avatar: 'assets/images/ella-dahl.jpg'
    description: "Ella, vild med at skrive."
  vedrana:
    name: Vedrana
    display_name: Vedrana
    description: "Vedrana, kan godt lide github, jekyll, html."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
permalinks:
  category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

